language: node_js
script: npm test
node_js:
- node
- '6'
- '4'
notifications:
  email: false
deploy:
  provider: npm
  email: npm@eli-white.com
  api_key:
    secure: RBiwiKmLgfke+wmouxqetW0ga28JCfQWE2bndgP7q1yMdmJ8viRE2zbpCZtLulIqFggokp480hgwXJxYQwfbjGV8ZmaeezYBjuBHS10ksEG45hkM+V8StwelXFC2yc+3sTWoHHrqcsUqOKR8N7e3vrSPsf09lRqPEFhAj8t0HYAuQB8jIpRsLasYawQIY+OBmF4CnAuQiL16OphJw8SpLwBagb0GW64xb1mPp2fYuCGQfj+nf6G16rsrcH+mECEVNqbWGhxeOxyHOlghgx7KpxMz6QSU8Gr4hf5WLEKONohawHprI0IBeRMnLn6ENWzkIikP7VLn433up+UznmYSJudLdTxJpJPGsSeTlvh5RsdmQRWeaLyoOQlxig1RyHtoo6ahXQdCja7B0A11x+TA9IdAlfHM0AQm2ZXD1MPusVA8u1ZnnXf/CSO9RxP+b3l4m28AdFoeQj3J+zFCErti1zGLzlOpMh7AZB69D50KKwaiv0MsSv3CsWlimNoCxb+A+P3ZoCEb7CWNYxYCCD63hkp4d4Qz5EDAUpOa9cSwhmx/B8kourbpQR/YN34IsDE7HdmdIaXY6cBmClhkwYgEBIp8O774cQvTkzZGmE4JDMmyWPqdtB9NtCIyrIkoyohh0VrvRprB9e1Ut2H38+ULOSjJEmoKp3E6S9cdfktHl6U=
  on:
    tags: true
    repo: TheSavior/grunt-before-after-hooks
    node: node
